server:
  port: 5000 # Elastic Beanstalk expects for Spring Boot Java apps to be deployed on port 5000...

spring:
  application:
    name: spring-boot-poc
  h2:
    console:
      enabled:
      path: /h2
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default

logging:
  level:
    org:
      hibernate: INFO
      SQL: DEBUG
      cache: DEBUG
      stat: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"