server:
  port: 5000 # Elastic Beanstalk expects for Spring Boot Java apps to be deployed on port 5000...

spring:
  application:
    name: spring-boot-poc
  h2:
    console:
      enabled:
      path: /h2
  datasource:
    url: jdbc:postgresql://java-react-training-course-db.crpipnhq23xz.us-west-1.rds.amazonaws.com:5432/postgres?currentSchema=project2
    driver-class-name: org.postgresql.Driver
    username: sean_taba
    password: Sean-Java-React-Course
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default

logging:
  level:
    org:
      hibernate: INFO
#              SQL: DEBUG
#              cashe: DEBUG
#              stat: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"